import type { Metadata } from "next";
import { Sedan } from "next/font/google";
import "./globals.css";

const SedanFont = Sedan({ weight: "400", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Date Custom Date Range Picker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={SedanFont.className}>{children}</body>
    </html>
  );
}
